// @ts-nocheck
export const CATEGORIES = [
  {
    id: "miles",
    label: "Miles",
    emoji: "🏃",
    iconCategory: "distance",
    description: "Most distance",
    detailedDescription: "Most miles ran",
    gradient: ["#3b82f6", "#60a5fa"],
  },
  {
    id: "runs",
    label: "Runs",
    emoji: "❤️‍🔥",
    iconCategory: "runs",
    description: "Most runs",
    detailedDescription: "Most runs",
    gradient: ["#0ea5e9", "#38bdf8"],
  },
  {
    id: "elevation",
    label: "Elevation",
    emoji: "⛰️",
    iconCategory: "elevation",
    description: "Most elevation",
    detailedDescription: "Most elevation climbed",
    gradient: ["#06b6d4", "#22d3ee"],
  },
  {
    id: "speed",
    label: "Speed",
    emoji: "🏎️",
    iconCategory: "pace",
    description: "Fastest pace",
    detailedDescription: "Fastest average pace ran",
    gradient: ["#14b8a6", "#2dd4bf"],
  },
  {
    id: "time",
    label: "Time",
    emoji: "⏳",
    iconCategory: "time",
    description: "Most time",
    detailedDescription: "Most time spent running or walking",
    gradient: ["#10b981", "#34d399"],
  },
  {
    id: "calories",
    label: "Calories",
    emoji: "💪",
    iconCategory: "calories",
    description: "Most calories",
    detailedDescription: "Most calories burnt",
    gradient: ["#22c55e", "#4ade80"],
  },
  {
    id: "heat",
    label: "Heat",
    emoji: "🔥",
    iconCategory: "heat",
    description: "Hottest temp",
    detailedDescription: "The highest average temperature ran at",
    gradient: ["#84cc16", "#a3e635"],
  },
  {
    id: "icy",
    label: "Cold",
    emoji: "🥶",
    iconCategory: "cold",
    description: "Coldest temp",
    detailedDescription: "The lowest average temperature ran at",
    gradient: ["#eab308", "#fde047"],
  },
  {
    id: "steps",
    label: "Steps",
    emoji: "👣",
    iconCategory: "steps",
    description: "Most steps",
    detailedDescription: "The most steps taken",
    gradient: ["#f59e0b", "#fbbf24"],
  },
  {
    id: "earlybird",
    label: "Early Bird",
    emoji: "🌅",
    iconCategory: "earlybird",
    description: "Early bird runs",
    detailedDescription: "Most runs started before 6am",
    gradient: ["#f97316", "#fb923c"],
  },
  {
    id: "nightowl",
    label: "Night Owl",
    emoji: "🌙",
    iconCategory: "nightowl",
    description: "Night owl runs",
    detailedDescription: "Most runs started after 8pm",
    gradient: ["#ec4899", "#f472b6"],
  },
  {
    id: "petpaced",
    label: "Pet Paced",
    emoji: "🐕",
    iconCategory: "pet",
    description: "Pet paced miles",
    detailedDescription: "Most miles ran with a pet",
    gradient: ["#d946ef", "#e879f9"],
  },
  {
    id: "unstoppable",
    label: "Unstoppable",
    emoji: "🤩",
    iconCategory: "unstoppable",
    description: "Unstoppable vibes",
    detailedDescription: "Most often felt unstoppable during their runs",
    gradient: ["#a855f7", "#c084fc"],
  },
  {
    id: "relaxed",
    label: "Easy & relaxed",
    emoji: "😌",
    iconCategory: "relaxed",
    description: "Most relaxed",
    detailedDescription:
      "Most often felt at ease and relaxed during their runs",
    gradient: ["#8b5cf6", "#a78bfa"],
  },
  {
    id: "grinding",
    label: "Grinding",
    emoji: "😤",
    iconCategory: "grinding",
    description: "Grinding vibes",
    detailedDescription:
      "Most often felt like they were grinding during their runs",
    gradient: ["#6366f1", "#818cf8"],
  },
  {
    id: "focused",
    label: "Focused",
    emoji: "🧠",
    iconCategory: "focused",
    description: "Most focused",
    detailedDescription: "Most often felt focused during their runs",
    gradient: ["#3b82f6", "#60a5fa"],
  },
  {
    id: "happy",
    label: "Happy miles",
    emoji: "😄",
    iconCategory: "happy",
    description: "Happy vibes",
    detailedDescription: "Most often felt happy during their runs",
    gradient: ["#0ea5e9", "#38bdf8"],
  },
  {
    id: "meh",
    label: "Meh",
    emoji: "😐",
    iconCategory: "meh",
    description: "Just exercising",
    detailedDescription: "Most often felt meh during their runs",
    gradient: ["#06b6d4", "#22d3ee"],
  },
  {
    id: "clearing",
    label: "Clearing head",
    emoji: "🌧️",
    iconCategory: "clearing",
    description: "Clearing the mind",
    detailedDescription:
      "Most often felt like they were clearing their head during their runs",
    gradient: ["#14b8a6", "#2dd4bf"],
  },
  {
    id: "race",
    label: "Race mode",
    emoji: "🏁",
    iconCategory: "race",
    description: "Race mode vibes",
    detailedDescription:
      "Most often felt like they were in race mode during their runs",
    gradient: ["#64748b", "#94a3b8"],
  },
];

export const PERIODS = [
  { id: "week", label: "W" },
  { id: "month", label: "M" },
];

export const SOCIAL_FILTERS = [
  { id: "everyone", label: "Everyone" },
  { id: "following", label: "Following" },
  { id: "followers", label: "Followers" },
];

export const LOCATION_FILTERS = [
  { id: "city", label: "City" },
  { id: "state", label: "State" },
  { id: "country", label: "Country" },
  { id: "global", label: "Global" },
];
